[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # version = "0.0.5"
  source = "github.com/ZackButcher/operator-sdk"
  branch = "non-internal"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/gogo/googleapis"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "istio.io/api"
  branch = "release-1.0"

[[constraint]]
  name = "istio.io/istio"
  version = "release-1.0"

