apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .gateway.name }}
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: "{{ .cluster.tunnelPort }}"
      protocol: HTTP
      name: http
